Desktop/motivate/main/dashboard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # dashboard
    path('', views.index, name='index'),

    # customer pages
    path('createCustomer/', views.createCustomer, name='createCustomer'),
    path('customer-list/', views.customerList, name='customerList'),
    path('customer/<str:pk_id>/', views.customerPage, name='customerPage'),
    path('customer/<str:pk_id>/paymentdetail/', views.customerPaymentList, name='customerPaymentList'),
    path('customer/<str:pk_id>/customer-property-list/', views.customerPropertyList, name='customerPropertyList'),
    
    # property pages
    path('propertyList/', views.propertyList, name='propertyList'),
    path('create-property-page/', views.createProperty, name='createProperty'),
    path('property-details/<str:pk_id>/', views.propertydetails, name='propertydetails'),

    # for purchases
    path('payment-list/', views.paymentpage, name='paymentpage'),

    # Documents
    path('customer/<str:pk_id>/openCustomerReceipt/', views.receipts, name='receipts'),
    path('download/<str:pk_id>/openCustomerReceipt/', views.downloadreceipt, name='downloadreceipt'),
    
    # message
    path('customer/<str:pk_id>/message', views.sendMessage, name='sendMessage'),
    path('customer/<str:pk_id>/whatappMessage', views.whatappMessage),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

Desktop/motivate/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('dashboard.urls')),
    path('message/', include('message.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

Desktop/motivate/main/dashboard/models.py
from django.db import models

class Customer(models.Model):

    TITLE = (
        ('Mr', 'Mr'),
        ('Mrs', 'Mrs'),
        ('Miss', 'Miss'),
        ('Others', 'Others'),
    )
    
    MARITALSTATUS = (
        ('Single', 'Single'),
        ('Married', 'Married'),
        ('Divorce', 'Divorce'),
        ('Widowed', 'Widowed'),
        ('Others', 'Others'),
    )

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    )

    HEARD_ABOUT_US = (
        ('Radio Station', 'Radio Station'),
        ('Magazine', 'Magazine'),
        ('Newspaper', 'Newspaper'),
        ('Facebook', 'Facebook'),
        ('Website', 'Website'),
        ('A friend', 'A friend'),
        ('Somewhere Online', 'Somewhere Online'),
    ) 

    title = models.CharField(max_length=100, choices=TITLE, default=MARITALSTATUS[-1])
    surname = models.CharField(max_length=100)
    firstName = models.CharField(max_length=100)

    passport = models.ImageField(null=True, blank=True, upload_to="images/")

    otherName = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, default=GENDER[-1])
    maritalstatus = models.CharField(max_length=100, choices=MARITALSTATUS, default=MARITALSTATUS[-1])
    maidenName  = models.CharField(max_length=100, null=True, blank=True)
    dateOfBirth  = models.DateField()

    email = models.EmailField(max_length=100, null=True, blank=True)
    phoneNumber = models.CharField(max_length=100, null=True, blank=True)
    homeTelephone = models.CharField(max_length=100, null=True, blank=True)
    customerHomeAddress = models.CharField(max_length=1000, null=True, blank=True)
    heard_about_us = models.CharField(max_length=100, choices=HEARD_ABOUT_US, default=HEARD_ABOUT_US[-1])
    heard_about_person = models.CharField(max_length=100, null=True, blank=True)
 
    # Next of Kin
    nk_fullName = models.CharField(max_length=100, null=True, blank=True)
    nk_telephone = models.CharField(max_length=100, null=True, blank=True)
    nk_email = models.CharField(max_length=100, null=True, blank=True)
 
    # Employment Details
    employer = models.CharField(max_length=100, null=True, blank=True)
    em_designation = models.CharField(max_length=100, null=True, blank=True)
    em_telephone = models.CharField(max_length=100, null=True, blank=True)
    em_address = models.CharField(max_length=100, null=True, blank=True)
    dateRegistered  = models.DateTimeField(auto_now_add=True, null=True)
    
    def fullname(self):
        surname = self.surname
        firstName = self.firstName
        fullname = surname + firstName
        return fullname

    def __str__(self):
        return self.title +  " " + self.surname + " " + self.firstName

class Property(models.Model): 
    name = models.CharField(max_length=100, null=True)
    price = models.IntegerField(null=True)
    location = models.CharField(max_length=500, null=True)
    quantity = models.IntegerField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Properties'

    def __str__(self):
        return self.name

    # To get quantity sold remaining
    def remainQuantity(self):
        purchase = self.purchase_set.all()
        if purchase:
            totalSold = 0
            for eachpurchase in purchase:
                totalSold += int(eachpurchase.quantity)
            remain = int(self.quantity) - int(totalSold)
            return remain
        else:
            pass

    # To get total quantity sold
    def soldQuantity(self):
        purchase = self.purchase_set.all()
        if purchase:
            totalSold = 0
            for eachpurchase in purchase:
                totalSold += int(eachpurchase.quantity)
            return totalSold
        else:
            pass


class Purchase(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE, related_name='orders')
    propertypurchase = models.ForeignKey(Property, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    actual_payment = models.IntegerField(default='0', null=True)

    def __str__(self):
        purchasedCustomer = str(self.customer)
        purchasedProperty = str(self.propertypurchase)
        date_createdpurchase = str(self.date_created)
        #theid = str(self.pk)
        return str(purchasedCustomer + ' for ' + purchasedProperty + ' - ' + date_createdpurchase)

    # Total paid on the purchase
    def totalPaid(self):
        payment = self.customerpayment.all()
        if payment:
            balance = 0
            for eachpayment in payment:
                balance += eachpayment.depositpayment
            return balance

    # Remaining balance on the purchase
    def balance_to_pay(self):
        payment = self.customerpayment.all()
        if payment:
            balance = 0
            for eachpayment in payment:
                balance += eachpayment.depositpayment
                totalDeposit = balance
            
            balanceToPay = self.actual_payment - totalDeposit

            return balanceToPay
        else:
            return(self.actual_payment)

    # Percent paid
    def percentPaid(self):
        payment = self.customerpayment.all()
        if payment:
            totalPaid = 0
            for eachpayment in payment:
                totalPaid += eachpayment.depositpayment
            

            x = (totalPaid * 100) / self.actual_payment
            content = str(round(x)) + '%'
            return content
        else:
            pass


    def dateStrip(self):
        date = str(self.date_created.date()).split(",", 1)[0]
        return date

class Payment(models.Model):
    PAYMENTPLAN = (
        ('outright', 'outright'),
        ('3 month installment', '3 month installment'),
        ('6 month installment', '6 month installment'),
        ('9 month installment', '9 month installment'),
        ('12 month installment', '12 month instalment'),
    )
    
    paymentplan = models.CharField(max_length=100, choices=PAYMENTPLAN, null=True)
    depositpayment = models.IntegerField(null=True)
    paymentMethod = models.CharField(max_length=100, null=True, blank=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    purchase = models.ForeignKey(Purchase, null=True, on_delete=models.CASCADE, related_name='customerpayment')

    def __str__(self):
        payment = str(self.paymentplan)
        customer = str(self.purchase.customer)
        propertyPurchase = str(self.purchase.propertypurchase)
        date_created = str(self.purchase.date_created)
        payment_display = customer + ' - ' + propertyPurchase + ' - ' + date_created
        return payment_display


    def percent(self):
        depositpayment = self.depositpayment
        Actual_payment = self.purchase.actual_payment

        if depositpayment == Actual_payment:
            content = "balanced" + "100%"
            return content
        
        elif depositpayment > Actual_payment:
            overpaid = depositpayment - Actual_payment 
            content = "balance overpaid" + str(round(overpaid))
            return content

        else:
            x = (depositpayment * 100) / Actual_payment
            content = str(round(x)) + '%'
            return content

    def dateStrip(self):
        date = str(self.date_created.date()).split(",", 1)[0]
        return date
 

Desktop/motivate/main/dashboard/forms.py
from django.forms import ModelForm
from .models import *

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'
        
class PropertyForm(ModelForm):
    class Meta:
        model = Property
        fields = '__all__'

class PaymentForm(ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'

Desktop/motivate/main/dashboard/templates/pages/customer/create-customer original.html
{% extends '../../base.html' %}

{% block content %}
 
<div class="container-fluid">
    <div class="row">
        <div class="heading">
            <h3>Create Customer Page</h3>
            <div class="location">Akinmorin</div>
        </div>
    </div>
 
<!-- form main container -->

    <div class="row">
        <div class="col card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Create Customer </h6>
            </div> 
            <div class="px-1 py-3 underline">
                <form class="col">
                    {% csrf_token %}
                    <!-- personal data fieldset --> 
                    <fieldset class="form-group border p-3">
                        <legend class="w-auto px-2">Personal Data and Contact</legend>
                        <div class="form-row">
                            
                            <div class="form-group col-sm-12">
                                <label for="id_title">Select<span class="text-danger">*</span></label>
                                <select name="title" id="id_title" class="form-control">
                                <option active>Title</option>
                                <option value="Mr">Mr</option>
                                <option value="Mrs">Mrs</option>
                                <option value="Miss">Miss</option>
                                <option value="Others">Others</option>
                                <option>...</option>
                                </select>
                            </div>

                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_surname">Surname Name<span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="surname" maxlength="100" required="" id="id_surname">
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_firstName">First Name<span class="text-danger">*</span></label>
                                <input type="text" class="form-control"  name="firstName" maxlength="100" required="" id="id_firstName">
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_otherName">Other Name</label>
                                <input type="text" class="form-control" name="otherName" maxlength="100" id="id_otherName">
                            </div>
                        </div>

                        <h5>Gender</h5>
                        <div class="form-row">

                                          
                            <div class="form-group col-sm-12">
                                <label for="id_gender">Select<span class="text-danger">*</span></label>
                                <select name="gender" id="id_gender" class="form-control">
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                    <option value="Others" selected="">Others</option>
                                    <option>...</option>
                                </select>
                            </div>      
 
                        </div>
                        
                        <div class="form-row">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="">Upload Passport</label>
                                <input type="file" class="form-control py-1" name="" id="">
                            </div>
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="id_maritalstatus">Marital Status<span class="text-danger">*</span></label>
                                <select name="maritalstatus" id="id_maritalstatus" class="form-control">
                                    <option>....</option>
                                    <option value="Single">Single</option>
                                    <option value="Married">Married</option>
                                    <option value="Divorce">Divorce</option>
                                    <option value="Widowed">Widowed</option>
                                    <option value="Others" selected="">Others</option>
                                </select>
                            </div>
                        </div>

                        
                        <div class="form-row">
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_maidenName">Maiden Name</label>
                                <input type="text" name="maidenName" maxlength="100" id="id_maidenName" class="form-control">
                            </div>

                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_dateOfBirth">Date of Birth<span class="text-danger">*</span></label>
                                <input type="text" name="dateOfBirth" maxlength="100" id="id_dateOfBirth" class="form-control">
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_email">Email</label>
                                <input type="text" name="email" maxlength="100" id="id_email" class="form-control">
                            </div>

                        </div>

                        <div class="form-row">
                        

                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_phoneNumber">Phone Numer <span class="text-danger">*</span></label>
                                <input type="text" name="phoneNumber" maxlength="100" id="id_phoneNumber" class="form-control">
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_homeTelephone"> Home Telephone</label>
                                <input type="text" class="form-control" name="homeTelephone" maxlength="100" id="id_homeTelephone">
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_customerHomeAddress">Customer Home Address<span class="text-danger">*</span></label>
                                <input type="textarea" class="form-control" name="customerHomeAddress" maxlength="1000" id="id_customerHomeAddress" placeholder="Apartment, studio, or floor">
                            </div>
                        </div>

                    </fieldset>

                    <!-- Next of king fieldset -->
                    <fieldset class="form-group border p-2">
                        <legend class="w-auto px-2">Next of Kin</legend>
                        <div class="form-row">
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="id_nk_fullName">Full Name</label>
                                <input type="text" name="nk_fullName" maxlength="100" id="id_nk_fullName" class="form-control">
                            </div>
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="id_nk_telephone">Telephone</label>
                                <input type="text" name="nk_telephone" maxlength="100" id="id_nk_telephone" class="form-control">
                            </div>
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="id_nk_email">Email</label>
                                <input type="text"  name="nk_email" maxlength="100" id="id_nk_email" class="form-control">
                            </div>
                        </div>

                    </fieldset>


                    <!-- Employment fieldset -->
                    <fieldset class="form-group border p-2">
                        <legend class="w-auto px-2 col">Current Employment Details</legend>
                        <div class="form-row">
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_employer">Employer</label>
                                <input type="text" name="employer" maxlength="100" id="id_employer" class="form-control">
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_em_designation">Designation</label>
                                <input type="text"  name="em_designation" maxlength="100" id="id_em_designation" class="form-control">
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_em_telephone">Telephone</label>
                                <input type="text" name="em_telephone" maxlength="100" id="id_em_telephone" class="form-control">
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_em_address">Address</label>
                                <input type="text" name="em_address" maxlength="100" id="id_em_address" class="form-control">
                            </div>
                        </div>
                    </fieldset>

                    <div class="form-group col-lg-4 col-sm-12">
                        <label for="id_heard_about_us">HOW DID YOU HEAR ABOUT US?<span class="text-danger">*</span> </label>
                        <select name="heard_about_us" id="id_heard_about_us" class="form-control">
                            <option value="Radio Station">Radio Station</option>
                            <option value="Magazine">Magazine</option>
                            <option value="Newspaper">Newspaper</option>
                            <option value="Facebook">Facebook</option>
                            <option value="Website">Website</option>
                            <option value="A friend">A friend</option>
                            <option value="Somewhere Online" selected="">Somewhere Online</option>
                            <option>...</option>
                        </select>
                    </div>

                    <!-- property fieldset -->
                   <div class="col-lg-4 col-sm-12">
                       <marquee behavior="" direction="">Confirm to fill input with red astericks ( <span class="text-danger">*</span> )</marquee>
                   </div>
                    <input type="submit" value="Create Customer Data" class="btn btn-primary">
                </form>
            </div>
        </div>


    </div>

</div>



{% endblock %}

Desktop/motivate/main/dashboard/templates/pages/customer/create-customer.html
{% extends '../../base.html' %}

{% block content %}
 <head>
     <style>
         input, select{
                        
            display: block;
            width: 100%;
            height: calc(1.5em + 0.75rem + 2px);
            padding: 0.375rem 0.75rem;
            font-size: 1rem;
            font-weight: 400;
            line-height: 1.5;
            color: #6e707e;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #d1d3e2;
            border-radius: 0.35rem;
         }
     </style>
 </head>
<div class="container-fluid">
    <div class="row">
        <div class="heading">
            <h3>Create Customer Page</h3>
            <!-- <div class="location"></div> -->
        </div>
    </div>
 
<!-- form main container -->

    <div class="row">
        <div class="col card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Create Customer <span class="text-warning">Step 1</span> </h6>
            </div> 
            <div class="px-1 py-3 underline">
                <form class="col" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- personal data fieldset --> 
                    <fieldset class="form-group border p-3">
                        <legend class="w-auto px-2">Personal Data and Contact</legend>
                        <div class="form-row">
                            
                            <div class="form-group col-sm-12">
                                <label for="id_title">Select<span class="text-danger">*</span></label>
                                {{form.title}}
                               
                            </div>

                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_surname">Surname Name<span class="text-danger">*</span></label>
                                {{form.surname}}
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_firstName">First Name<span class="text-danger">*</span></label>
                                <input type="text" class="form-control"  name="firstName" maxlength="100" required="" id="id_firstName">
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_otherName">Other Name</label>
                                {{form.otherName}}
                            </div>
                        </div>

                        <h5>Gender</h5>
                        <div class="form-row">

                                          
                            <div class="form-group col-sm-12">
                                <label for="id_gender">Select<span class="text-danger">*</span></label>
                                {{form.gender}}
                            </div>      
 
                        </div>
                        
                        <div class="form-row">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="">Upload Passport</label>
                                {{form.passport}}
                            </div>
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="id_maritalstatus">Marital Status<span class="text-danger">*</span></label>
                                {{form.maritalstatus}}
                            </div>
                        </div>

                        
                        <div class="form-row">
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_maidenName">Maiden Name</label>
                                {{form.maidenName}}
                            </div>

                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_dateOfBirth">Date of Birth <span class="text-danger">(YYYY-MM-DD)*</span></label>
                                {{form.dateOfBirth}}
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_email">Email</label>
                                {{form.email}}
                            </div>

                        </div>

                        <div class="form-row">
                        

                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_phoneNumber">Phone Numer <span class="text-danger">*</span></label>
                                {{form.phoneNumber}}
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_homeTelephone"> Home Telephone</label>
                                {{form.homeTelephone}}
                            </div>
                            <div class="form-group col-lg-4 col-sm-12">
                                <label for="id_customerHomeAddress">Customer Home Address<span class="text-danger">*</span></label>
                                {{form.customerHomeAddress}}
                            </div>
                        </div>

                    </fieldset>

                    <!-- Next of king fieldset -->
                    <fieldset class="form-group border p-2">
                        <legend class="w-auto px-2">Next of Kin</legend>
                        <div class="form-row">
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="id_nk_fullName">Full Name</label>
                                {{form.nk_fullName}}
                            </div>
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="id_nk_telephone">Telephone</label>
                                {{form.nk_telephone}}
                            </div>
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="id_nk_email">Email</label>
                                {{form.nk_email}}
                            </div>
                        </div>

                    </fieldset>


                    <!-- Employment fieldset -->
                    <fieldset class="form-group border p-2">
                        <legend class="w-auto px-2 col">Current Employment Details</legend>
                        <div class="form-row">
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_employer">Employer</label>
                                {{form.employer}}
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_em_designation">Designation</label>
                                {{form.em_designation}}
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_em_telephone">Telephone</label>
                                {{form.em_telephone}}
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="id_em_address">Address</label>
                                {{form.em_address}}
                            </div>
                        </div>
                    </fieldset>

                    <div class="form-group col-lg-4 col-sm-12">
                        <label for="id_heard_about_us">HOW DID YOU HEAR ABOUT US?<span class="text-danger">*</span> </label>
                                {{form.heard_about_us}}
                                <br>
                                <label for="id_em_address">Others:</label>
                                <!-- <p class="text-warning">If through friend;</p> -->
                                {{form.heard_about_person}}
                    </div>
                    <div>
                        {{msg}}
                    </div>
                    <!-- property fieldset -->
                   <div class="col-lg-4 col-sm-12">
                       <marquee behavior="" direction="">Confirm to fill input with red astericks ( <span class="text-danger">*</span> )</marquee>
                   </div>
                   <button type="submit" class="btn btn-primary">Create Customer Data</button>
                </form>
            </div>
        </div>


    </div>

</div>



{% endblock %}