Desktop/motivate/main/dashboard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # dashboard
    path('', views.index, name='index'),

    # customer pages
    path('createCustomer/', views.createCustomer, name='createCustomer'),
    path('customer-list/', views.customerList, name='customerList'),
    path('customer/<str:pk_id>/', views.customerPage, name='customerPage'),
    path('customer/<str:pk_id>/paymentdetail/', views.customerPaymentList, name='customerPaymentList'),
    path('customer/<str:pk_id>/customer-property-list/', views.customerPropertyList, name='customerPropertyList'),
    
    # property pages
    path('propertyList/', views.propertyList, name='propertyList'),
    path('create-property-page/', views.createProperty, name='createProperty'),
    path('property-details/<str:pk_id>/', views.propertydetails, name='propertydetails'),

    # for purchases
    path('payment-list/', views.paymentpage, name='paymentpage'),

    # Documents
    path('customer/<str:pk_id>/openCustomerReceipt/', views.receipts, name='receipts'),
    path('download/<str:pk_id>/openCustomerReceipt/', views.downloadreceipt, name='downloadreceipt'),
    
    # message
    path('customer/<str:pk_id>/message', views.sendMessage, name='sendMessage'),
    path('customer/<str:pk_id>/whatappMessage', views.whatappMessage),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

Desktop/motivate/main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('dashboard.urls')),
    path('message/', include('message.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

Desktop/motivate/main/dashboard/models.py
from django.db import models

class Customer(models.Model):

    TITLE = (
        ('Mr', 'Mr'),
        ('Mrs', 'Mrs'),
        ('Miss', 'Miss'),
        ('Others', 'Others'),
    )
    
    MARITALSTATUS = (
        ('Single', 'Single'),
        ('Married', 'Married'),
        ('Divorce', 'Divorce'),
        ('Widowed', 'Widowed'),
        ('Others', 'Others'),
    )

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    )

    HEARD_ABOUT_US = (
        ('Radio Station', 'Radio Station'),
        ('Magazine', 'Magazine'),
        ('Newspaper', 'Newspaper'),
        ('Facebook', 'Facebook'),
        ('Website', 'Website'),
        ('A friend', 'A friend'),
        ('Somewhere Online', 'Somewhere Online'),
    ) 

    title = models.CharField(max_length=100, choices=TITLE, default=MARITALSTATUS[-1])
    surname = models.CharField(max_length=100)
    firstName = models.CharField(max_length=100)

    passport = models.ImageField(null=True, blank=True, upload_to="images/")

    otherName = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, default=GENDER[-1])
    maritalstatus = models.CharField(max_length=100, choices=MARITALSTATUS, default=MARITALSTATUS[-1])
    maidenName  = models.CharField(max_length=100, null=True, blank=True)
    dateOfBirth  = models.DateField()

    email = models.EmailField(max_length=100, null=True, blank=True)
    phoneNumber = models.CharField(max_length=100, null=True, blank=True)
    homeTelephone = models.CharField(max_length=100, null=True, blank=True)
    customerHomeAddress = models.CharField(max_length=1000, null=True, blank=True)
    heard_about_us = models.CharField(max_length=100, choices=HEARD_ABOUT_US, default=HEARD_ABOUT_US[-1])
    heard_about_person = models.CharField(max_length=100, null=True, blank=True)
 
    # Next of Kin
    nk_fullName = models.CharField(max_length=100, null=True, blank=True)
    nk_telephone = models.CharField(max_length=100, null=True, blank=True)
    nk_email = models.CharField(max_length=100, null=True, blank=True)
 
    # Employment Details
    employer = models.CharField(max_length=100, null=True, blank=True)
    em_designation = models.CharField(max_length=100, null=True, blank=True)
    em_telephone = models.CharField(max_length=100, null=True, blank=True)
    em_address = models.CharField(max_length=100, null=True, blank=True)
    dateRegistered  = models.DateTimeField(auto_now_add=True, null=True)
    
    def fullname(self):
        surname = self.surname
        firstName = self.firstName
        fullname = surname + firstName
        return fullname

    def __str__(self):
        return self.title +  " " + self.surname + " " + self.firstName

class Property(models.Model): 
    name = models.CharField(max_length=100, null=True)
    price = models.IntegerField(null=True)
    location = models.CharField(max_length=500, null=True)
    quantity = models.IntegerField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Properties'

    def __str__(self):
        return self.name

    # To get quantity sold remaining
    def remainQuantity(self):
        purchase = self.purchase_set.all()
        if purchase:
            totalSold = 0
            for eachpurchase in purchase:
                totalSold += int(eachpurchase.quantity)
            remain = int(self.quantity) - int(totalSold)
            return remain
        else:
            pass

    # To get total quantity sold
    def soldQuantity(self):
        purchase = self.purchase_set.all()
        if purchase:
            totalSold = 0
            for eachpurchase in purchase:
                totalSold += int(eachpurchase.quantity)
            return totalSold
        else:
            pass


class Purchase(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE, related_name='orders')
    propertypurchase = models.ForeignKey(Property, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    actual_payment = models.IntegerField(default='0', null=True)

    def __str__(self):
        purchasedCustomer = str(self.customer)
        purchasedProperty = str(self.propertypurchase)
        date_createdpurchase = str(self.date_created)
        #theid = str(self.pk)
        return str(purchasedCustomer + ' for ' + purchasedProperty + ' - ' + date_createdpurchase)

    # Total paid on the purchase
    def totalPaid(self):
        payment = self.customerpayment.all()
        if payment:
            balance = 0
            for eachpayment in payment:
                balance += eachpayment.depositpayment
            return balance

    # Remaining balance on the purchase
    def balance_to_pay(self):
        payment = self.customerpayment.all()
        if payment:
            balance = 0
            for eachpayment in payment:
                balance += eachpayment.depositpayment
                totalDeposit = balance
            
            balanceToPay = self.actual_payment - totalDeposit

            return balanceToPay
        else:
            return(self.actual_payment)

    # Percent paid
    def percentPaid(self):
        payment = self.customerpayment.all()
        if payment:
            totalPaid = 0
            for eachpayment in payment:
                totalPaid += eachpayment.depositpayment
            

            x = (totalPaid * 100) / self.actual_payment
            content = str(round(x)) + '%'
            return content
        else:
            pass


    def dateStrip(self):
        date = str(self.date_created.date()).split(",", 1)[0]
        return date

class Payment(models.Model):
    PAYMENTPLAN = (
        ('outright', 'outright'),
        ('3 month installment', '3 month installment'),
        ('6 month installment', '6 month installment'),
        ('9 month installment', '9 month installment'),
        ('12 month installment', '12 month instalment'),
    )
    
    paymentplan = models.CharField(max_length=100, choices=PAYMENTPLAN, null=True)
    depositpayment = models.IntegerField(null=True)
    paymentMethod = models.CharField(max_length=100, null=True, blank=True)
    date_created  = models.DateTimeField(auto_now_add=True, null=True)
    purchase = models.ForeignKey(Purchase, null=True, on_delete=models.CASCADE, related_name='customerpayment')

    def __str__(self):
        payment = str(self.paymentplan)
        customer = str(self.purchase.customer)
        propertyPurchase = str(self.purchase.propertypurchase)
        date_created = str(self.purchase.date_created)
        payment_display = customer + ' - ' + propertyPurchase + ' - ' + date_created
        return payment_display


    def percent(self):
        depositpayment = self.depositpayment
        Actual_payment = self.purchase.actual_payment

        if depositpayment == Actual_payment:
            content = "balanced" + "100%"
            return content
        
        elif depositpayment > Actual_payment:
            overpaid = depositpayment - Actual_payment 
            content = "balance overpaid" + str(round(overpaid))
            return content

        else:
            x = (depositpayment * 100) / Actual_payment
            content = str(round(x)) + '%'
            return content

    def dateStrip(self):
        date = str(self.date_created.date()).split(",", 1)[0]
        return date
 

Desktop/motivate/main/dashboard/forms.py
from django.forms import ModelForm
from .models import *

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'
        
class PropertyForm(ModelForm):
    class Meta:
        model = Property
        fields = '__all__'

class PaymentForm(ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'

Desktop/motivate/main/dashboard/templates/pages/payment/all-purchases.html
{% extends 'base.html' %}



{% block content %}



    <!-- Begin Page Content -->
    <div class="container-fluid py-4 bg-primary">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-white ">Purchase Table</h1>
                
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Search Purchases</h6>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4 text-center">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">All Purchases</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered text-align-center" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Property</th>
                                <th>Property Location</th>
                                <th>Property Pricing</th>
                                <th>Total Plots purchased</th>
                            </tr>
                        </thead>
                        
                        <!-- Data for property from database -->
                        <tbody>
                            {% for Property in purchase %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ Property.propertypurchase }}</td>
                                <td>{{ Property.customer }}</td>
                                <td>{{ Property.propertypurchase.price }}</td>
                                <td>{{ Property.quantity }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% include 'footer.html' %}


{% endblock %}

Desktop/motivate/main/dashboard/templates/pages/payment/payment.html
{% extends 'base.html' %}

{% block content %}

<head>
    <style>
        input, select{
                    
        display: block;
        width: 100%;
        height: calc(1.5em + 0.75rem + 2px);
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #6e707e;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #d1d3e2;
        border-radius: 0.35rem;
        }

        .close_search{
            display: none;
        }
    </style>
</head> 

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">All Payments Available For Filtering</h1>

    <!-- Search container --> 
    <div class="card mb-4 shadow">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Look up payment Here</h6>
        </div>
        <div class="card-body">

        <button class="btn btn-info mb-4 mr-3" id="openSearch" onclick="openSearch()">Filter payment</button>

        <form action="">
            <div class="form-row col-lg-4 close_search" id="searchDiv">
                <table> 
                    <tbody>
                        <tr>
                            <td>Paymentplan</td>
                            <td>
                                <select name="paymentplan" id="id_paymentplan">
                                    <option value="" selected="">---------</option>
                                    <option value="outright">outright</option>
                                    <option value="3 month installment">3 month installment</option>
                                    <option value="6 month installment">6 month installment</option>
                                    <option value="9 month installment">9 month installment</option>
                                    <option value="12 month installment">12 month instalment</option>
                                </select>
                            </td>
                        </tr>
                        
                        <tr>
                            <td>PaymentMethod</td>
                            <td><input type="text" name="paymentMethod" id="id_paymentMethod"></td>
                        </tr>   
                        <tr>
                            <td>Date is greater than or equal to</td>
                            <td><input type="text" name="start_date" id="id_start_date"></td>
                        </tr>
                        <tr>
                            <td>Date is less than or equal to</td>
                            <td><input type="text" name="end_date" id="id_end_date"></td>
                        </tr>
                    </tbody>
                </table> 
                <button type="submit" class="btn btn-primary btn-block py-2 mt-3">Submit</button>
                <button class="btn btn-info mb-4 mt-4 mr-3" id="closeSearch" onclick="closeSearch()">close Filter</button>
            </div>
        </form> 
            
        </div>
    </div>

    
<script>
let purchaseDiv = document.getElementById("searchDiv")
let btn = document.getElementById("openSearch")
let clsBtn = document.getElementById("closeSearch")
const openSearch = () => {

    btn.addEventListener('click', ()=> {
        purchaseDiv.style.display = "block"
    
    })
}

const closeSearch = () => {

    clsBtn.addEventListener('click', ()=> {
        purchaseDiv.style.display = "none"
    
    })
}


</script>

    <!-- DataTables Customer DB Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Customer List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <div class="row">
                            <div class="col">
                                <!-- <span class="mb-4"><button id="viewByName" onclick="viewByName()" class="btn btn-info mr-3">View by Name</button><button onclick="viewByDate()" class="btn btn-info mr-3">View by Date</button></span> -->
                                <p id="customerCount">All Payments {{ customersDate.count }}</p>
                            </div>
                        </div>
                        <tr>
                            <th>No</th>
                            <th>Customer Name</th>
                            <th>Property</th>
                            <th>Payment</th>
                            <th>Date Registered</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot> 
                    <tbody>
                        <span id="customerLoop">{% for eachpayment in payment %}</span>
                        <tr class="position-relative">

                            <td>{{ forloop.counter }}</td>

                            <td>{{ eachpayment.purchase.customer }}</td>
                            <td>{{ eachpayment.purchase.propertypurchase }}</td>
                            <td>#{{ eachpayment.depositpayment }}</td>
                            <td>{{ eachpayment.dateStrip }}</td>
                            <td><a class="btn btn-primary" href="{% url 'customerPaymentList' eachpayment.purchase.customer.id %}">View</a></td>
                        </tr>
                        <span id="customerEndLoop">{% endfor %}</span>
                    </tbody>
                </table>

                

            </div>
        </div>
    </div>
    <!-- DataTables Ends -->

</div>
<!-- /.container-fluid -->

{% endblock %}